version: "3.9"

services:

  postgres:

    image: postgres:16

    container_name: astro-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: astroai

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:

    build: .

    container_name: astro-backend

    restart: always

    depends_on:
      - postgres

    env_file:
      - .env

    ports:
      - "8000:8000"

    volumes:
      - .:/app

volumes:
  postgres_data: